//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWCPaint.Wpf.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SWCPaint.Wpf.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скасувати.
        /// </summary>
        public static string ColorPicker_Cancel_Button {
            get {
                return ResourceManager.GetString("ColorPicker_Cancel_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Відтінок.
        /// </summary>
        public static string ColorPicker_Hue_Label {
            get {
                return ResourceManager.GetString("ColorPicker_Hue_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ОК.
        /// </summary>
        public static string ColorPicker_OK_Button {
            get {
                return ResourceManager.GetString("ColorPicker_OK_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Насиченість.
        /// </summary>
        public static string ColorPicker_Saturation_Label {
            get {
                return ResourceManager.GetString("ColorPicker_Saturation_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Яскравість.
        /// </summary>
        public static string ColorPicker_Value_Label {
            get {
                return ResourceManager.GetString("ColorPicker_Value_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вибір кольору.
        /// </summary>
        public static string ColorPicker_Window_Title {
            get {
                return ResourceManager.GetString("ColorPicker_Window_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Створити.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Шар.
        /// </summary>
        public static string Layer_Name {
            get {
                return ResourceManager.GetString("Layer_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фон.
        /// </summary>
        public static string Layer_NewProject_Background {
            get {
                return ResourceManager.GetString("Layer_NewProject_Background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Видалити.
        /// </summary>
        public static string Layer_Remove_Action {
            get {
                return ResourceManager.GetString("Layer_Remove_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перейменувати.
        /// </summary>
        public static string Layer_Rename_Action {
            get {
                return ResourceManager.GetString("Layer_Rename_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введіть нову назву шару:.
        /// </summary>
        public static string Layer_Rename_Prompt {
            get {
                return ResourceManager.GetString("Layer_Rename_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перейменування.
        /// </summary>
        public static string Layer_Rename_Title {
            get {
                return ResourceManager.GetString("Layer_Rename_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Шари.
        /// </summary>
        public static string Layers_View_Title {
            get {
                return ResourceManager.GetString("Layers_View_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Правка.
        /// </summary>
        public static string Menu_Edit_Action {
            get {
                return ResourceManager.GetString("Menu_Edit_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вихід.
        /// </summary>
        public static string Menu_Exit_Action {
            get {
                return ResourceManager.GetString("Menu_Exit_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Експортувати як зображення....
        /// </summary>
        public static string Menu_ExportAsImage_Action {
            get {
                return ResourceManager.GetString("Menu_ExportAsImage_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файл.
        /// </summary>
        public static string Menu_File_Action {
            get {
                return ResourceManager.GetString("Menu_File_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Завантажити проєкт....
        /// </summary>
        public static string Menu_LoadProject_Action {
            get {
                return ResourceManager.GetString("Menu_LoadProject_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новий проєкт....
        /// </summary>
        public static string Menu_NewProject_Action {
            get {
                return ResourceManager.GetString("Menu_NewProject_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Повторити дію.
        /// </summary>
        public static string Menu_Redo_Action {
            get {
                return ResourceManager.GetString("Menu_Redo_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зберегти проєкт....
        /// </summary>
        public static string Menu_SaveProject_Action {
            get {
                return ResourceManager.GetString("Menu_SaveProject_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Відмінити дію.
        /// </summary>
        public static string Menu_Undo_Action {
            get {
                return ResourceManager.GetString("Menu_Undo_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дію повернуто.
        /// </summary>
        public static string Paint_Redo_Status {
            get {
                return ResourceManager.GetString("Paint_Redo_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Готово.
        /// </summary>
        public static string Paint_Status_Ready {
            get {
                return ResourceManager.GetString("Paint_Status_Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дію відмінено.
        /// </summary>
        public static string Paint_Undo_Status {
            get {
                return ResourceManager.GetString("Paint_Undo_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paint.
        /// </summary>
        public static string Paint_Window_Title {
            get {
                return ResourceManager.GetString("Paint_Window_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обрати колір....
        /// </summary>
        public static string Project_BackgroundColor_Button {
            get {
                return ResourceManager.GetString("Project_BackgroundColor_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Колір фону.
        /// </summary>
        public static string Project_BackgroundColor_Label {
            get {
                return ResourceManager.GetString("Project_BackgroundColor_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Відмінити.
        /// </summary>
        public static string Project_Cancel_Button {
            get {
                return ResourceManager.GetString("Project_Cancel_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Створити.
        /// </summary>
        public static string Project_Create_Button {
            get {
                return ResourceManager.GetString("Project_Create_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Без назви.
        /// </summary>
        public static string Project_ExportAsImage_FileName {
            get {
                return ResourceManager.GetString("Project_ExportAsImage_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PNG зображення.
        /// </summary>
        public static string Project_ExportAsImage_FileType {
            get {
                return ResourceManager.GetString("Project_ExportAsImage_FileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Експортовано як зображення успішно.
        /// </summary>
        public static string Project_ExportAsImage_Status {
            get {
                return ResourceManager.GetString("Project_ExportAsImage_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Помилка при збереженні зображення.
        /// </summary>
        public static string Project_ExportAsImageFailed_Status {
            get {
                return ResourceManager.GetString("Project_ExportAsImageFailed_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Висота холста за межами дозволених значень.
        /// </summary>
        public static string Project_Height_Error {
            get {
                return ResourceManager.GetString("Project_Height_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Висота.
        /// </summary>
        public static string Project_Height_Label {
            get {
                return ResourceManager.GetString("Project_Height_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проєкт завантажено.
        /// </summary>
        public static string Project_Load_Status {
            get {
                return ResourceManager.GetString("Project_Load_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Помилка при завантаженні проєкту.
        /// </summary>
        public static string Project_LoadFailed_Status {
            get {
                return ResourceManager.GetString("Project_LoadFailed_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Створено новий проєкт.
        /// </summary>
        public static string Project_New_Status {
            get {
                return ResourceManager.GetString("Project_New_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новий проєкт.
        /// </summary>
        public static string Project_New_Title {
            get {
                return ResourceManager.GetString("Project_New_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paint Проєкт.
        /// </summary>
        public static string Project_Open_FileType {
            get {
                return ResourceManager.GetString("Project_Open_FileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новий проєкт.
        /// </summary>
        public static string Project_Save_FileName {
            get {
                return ResourceManager.GetString("Project_Save_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проєкт успішно збережено.
        /// </summary>
        public static string Project_Save_Status {
            get {
                return ResourceManager.GetString("Project_Save_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сталася помилка при збереженні проєкту.
        /// </summary>
        public static string Project_SaveFailed_Status {
            get {
                return ResourceManager.GetString("Project_SaveFailed_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ширина холста за межами дозволених значень.
        /// </summary>
        public static string Project_Width_Error {
            get {
                return ResourceManager.GetString("Project_Width_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ширина.
        /// </summary>
        public static string Project_Width_Label {
            get {
                return ResourceManager.GetString("Project_Width_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пензель.
        /// </summary>
        public static string Tool_Brush_Name {
            get {
                return ResourceManager.GetString("Tool_Brush_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Еліпс.
        /// </summary>
        public static string Tool_Ellipse_Name {
            get {
                return ResourceManager.GetString("Tool_Ellipse_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Гумка.
        /// </summary>
        public static string Tool_Eraser_Name {
            get {
                return ResourceManager.GetString("Tool_Eraser_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лінія.
        /// </summary>
        public static string Tool_Line_Name {
            get {
                return ResourceManager.GetString("Tool_Line_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Олівець.
        /// </summary>
        public static string Tool_Pencil_Name {
            get {
                return ResourceManager.GetString("Tool_Pencil_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прямокутник.
        /// </summary>
        public static string Tool_Rectangle_Name {
            get {
                return ResourceManager.GetString("Tool_Rectangle_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обрано інструмент.
        /// </summary>
        public static string Tool_Select_Status {
            get {
                return ResourceManager.GetString("Tool_Select_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Помилка при обранні інструмента.
        /// </summary>
        public static string Tool_SelectFailed_Status {
            get {
                return ResourceManager.GetString("Tool_SelectFailed_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кольори.
        /// </summary>
        public static string Toolbar_Colors_Label {
            get {
                return ResourceManager.GetString("Toolbar_Colors_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Колір заливки.
        /// </summary>
        public static string Toolbar_FillColor_Tooltip {
            get {
                return ResourceManager.GetString("Toolbar_FillColor_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Повторити дію.
        /// </summary>
        public static string Toolbar_Redo_Tooltip {
            get {
                return ResourceManager.GetString("Toolbar_Redo_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Колір обведення.
        /// </summary>
        public static string Toolbar_StrokeColor_Tooltip {
            get {
                return ResourceManager.GetString("Toolbar_StrokeColor_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Товщина.
        /// </summary>
        public static string Toolbar_Thickness_Label {
            get {
                return ResourceManager.GetString("Toolbar_Thickness_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Відмінити дію.
        /// </summary>
        public static string Toolbar_Undo_Tooltip {
            get {
                return ResourceManager.GetString("Toolbar_Undo_Tooltip", resourceCulture);
            }
        }
    }
}
